openapi: 3.0.0
info:
  title: Categories API
  description: API for managing categories
  version: 1.0.0
paths:
  /api/category/create:
    post:
      summary: Create a new category
      tags:
        - Categories
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryName:
                  type: string
                  description: Name of the category
                  example: Technology
                description:
                  type: string
                  description: Description of the category
                  example: All about technology
      responses:
        '201':
          description: Category created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /api/category:
    get:
      summary: Get all categories
      tags:
        - Categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /api/category/update/{id}:
    put:
      summary: Update a category
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the category to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryName:
                  type: string
                  description: Name of the category
                  example: Technology
                description:
                  type: string
                  description: Description of the category
                  example: All about technology
      responses:
        '200':
          description: Category updated successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Category not found
  /api/category/{id}:
    get:
      summary: Get a category by ID
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the category to retrieve
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
  /api/category/delete/{id}:
    delete:
      summary: Delete a category
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the category to delete
      responses:
        '200':
          description: Category deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Category not found
components:
  schemas:
    Category:
      type: object
      required:
        - categoryName
      properties:
        id:
          type: string
          description: The auto-generated id of the category
        categoryName:
          type: string
          description: Name of the category
        description:
          type: string
          description: Description of the category
        posts:
          type: array
          items:
            type: string
          description: List of post IDs associated with the category
        author:
          type: string
          description: ID of the user who created the category
        createdAt:
          type: string
          format: date-time
          description: The date the category was created
        updatedAt:
          type: string
          format: date-time
          description: The date the category was last updated
      example:
        id: 60d0fe4f5311236168a109ca
        categoryName: Technology
        description: All about technology
        posts: []
        author: 60d0fe4f5311236168a109cb
        createdAt: 2021-06-21T12:34:56.789Z
        updatedAt: 2021-06-21T12:34:56.789Z
