openapi: 3.0.0
info:
  title: Payments API
  description: API for managing payments
  version: 1.0.0
paths:
  /api/payment/checkout:
    post:
      summary: Create a new payment
      tags:
        - Payments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                  description: Payment reference
                  example: REF123456
                currency:
                  type: string
                  description: Currency of the payment
                  example: USD
                subscriptionPlan:
                  type: string
                  description: ID of the subscription plan
                  example: 60d0fe4f5311236168a109cc
                amount:
                  type: number
                  description: Amount to be paid
                  example: 49.99
      responses:
        '201':
          description: Payment created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /api/payment/verify/{paymentId}:
    get:
      summary: Verify a payment
      tags:
        - Payments
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: paymentId
          schema:
            type: string
          required: true
          description: ID of the payment to verify
      responses:
        '200':
          description: Payment verified successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Payment not found
  /api/payment/free:
    get:
      summary: Free payment
      tags:
        - Payments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Free payment processed successfully
        '401':
          description: Unauthorized
components:
  schemas:
    Payment:
      type: object
      required:
        - reference
        - currency
        - subscriptionPlan
        - amount
      properties:
        id:
          type: string
          description: The auto-generated id of the payment
        user:
          type: string
          description: ID of the user who made the payment
        reference:
          type: string
          description: Payment reference
        currency:
          type: string
          description: Currency of the payment
        status:
          type: string
          description: Status of the payment
        subscriptionPlan:
          type: string
          description: ID of the subscription plan
        amount:
          type: number
          description: Amount to be paid
        createdAt:
          type: string
          format: date-time
          description: The date the payment was created
        updatedAt:
          type: string
          format: date-time
          description: The date the payment was last updated
      example:
        id: 60d0fe4f5311236168a109cd
        user: 60d0fe4f5311236168a109ca
        reference: REF123456
        currency: USD
        status: pending
        subscriptionPlan: 60d0fe4f5311236168a109cc
        amount: 49.99
        createdAt: 2021-06-21T12:34:56.789Z
        updatedAt: 2021-06-21T12:34:56.789Z
