openapi: 3.0.0
info:
  title: Plans API
  description: API for managing subscription plans
  version: 1.0.0
paths:
  /api/plan/create:
    post:
      summary: Create a new plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
      responses:
        '201':
          description: Plan created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /api/plan:
    get:
      summary: Get all plans
      tags:
        - Plans
      responses:
        '200':
          description: A list of plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'
        '400':
          description: Bad request
  /api/plan/update/{id}:
    put:
      summary: Update a plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the plan to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
      responses:
        '200':
          description: Plan updated successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Plan not found
  /api/plan/{id}:
    get:
      summary: Get a plan by ID
      tags:
        - Plans
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the plan to retrieve
      responses:
        '200':
          description: Plan retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
        '400':
          description: Bad request
        '404':
          description: Plan not found
  /api/plan/delete/{id}:
    delete:
      summary: Delete a plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the plan to delete
      responses:
        '200':
          description: Plan deleted successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Plan not found
components:
  schemas:
    Plan:
      type: object
      required:
        - planName
        - features
        - price
        - user
      properties:
        id:
          type: string
          description: The auto-generated id of the plan
        planName:
          type: string
          description: Name of the plan
        features:
          type: array
          items:
            type: string
          description: Features included in the plan
        price:
          type: number
          description: Price of the plan
        limitation:
          type: string
          description: Limitations of the plan
        user:
          type: string
          description: ID of the user who created the plan
        createdAt:
          type: string
          format: date-time
          description: The date the plan was created
        updatedAt:
          type: string
          format: date-time
          description: The date the plan was last updated
      example:
        id: 60d0fe4f5311236168a109cd
        planName: Basic Plan
        features:
          - Feature 1
          - Feature 2
        price: 9.99
        limitation: Limited to 10 users
        user: 60d0fe4f5311236168a109ca
        createdAt: 2021-06-21T12:34:56.789Z
        updatedAt: 2021-06-21T12:34:56.789Z
